language: php
php: ["7.2"]
sudo: false
dist: trusty

install:
- "wget -O - https://poggit.pmmp.io/res/travisInstall.sh | bash -s - || true"

script:
- "if [ -f ${TRAVIS_BUILD_DIR}/../PocketMine/unstaged/MissingItems-McpeBooster.phar ] ; then wget -O - https://poggit.pmmp.io/res/travisScript.sh | bash -s - MissingItems-McpeBooster MissingItems-McpeBooster ; else true ; fi"
